name: 'Lighthouse Check'
description: 'GitHub Action for running one or multiple Lighthouse audits featuring PR comments, Slack notifications and more!'
inputs:
  apiToken:
    description: 'The automated-lighthouse-check.com account API token found in the dashboard.'
  author:
    description: 'For Slack notifications: A user handle, typically from GitHub.'
  awsAccessKeyId:
    description: 'The AWS accessKeyId for an S3 bucket.'
  awsBucket:
    description: 'The AWS Bucket for an S3 bucket.'
  awsRegion:
    description: 'The AWS region for an S3 bucket.'
  awsSecretAccessKey:
    description: 'The AWS secretAccessKey for an S3 bucket.'
  branch:
    description: 'For Slack notifications: A version control branch, typically from GitHub.'
  configFile:
    description: 'A configuration file path in JSON format which holds all options defined here. This file should be relative to the file being interpretted. In this case it will most likely be the root of the repo ("./")'
  emulatedFormFactor:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module for details.'
  extraHeaders:
    description: 'Stringified HTTP Header object key/value pairs to send in requests. example: <code>"{\"Cookie\":\"monster=blue\", \"x-men\":\"wolverine\"}"'
  locale:
    description: 'A locale for Lighthouse reports. Example: ja'
  outputDirectory:
    description: 'An absolute directory path to output report. You can do this an an alternative or combined with an S3 upload.'
  pr:
    description: 'For Slack notifications: A version control pull request URL, typically from GitHub.'
  accessToken:
    description: 'Access token of a user to post PR comments.'
  sha:
    description: 'For Slack notifications: A version control sha, typically from GitHub.'
  slackWebhookUrl:
    description: 'A Slack Incoming Webhook URL to send notifications to.'
  tag:
    description: 'An optional tag or name (example: "build #2" or "v0.0.2").'
  throttlingMethod:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module comments for details.'
  throttling:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module comments for details.'
  timeout:
    description: 'Minutes to timeout for remote runs. If "wait" option is "true" (it is by default), we wait for results. If this timeout is met before results are received an error is thrown.'
  urls:
    description: 'A comma-separated list of URLs (or page API tokens if running remotely).'
  verbose:
    description: 'If yes, logs output along each step.'
  wait:
    description: 'If "true", for remote runs, waits for all audit results to be returned, otherwise URLs are only enqueued.'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'zap'  
  color: 'green'