name: 'Lighthouse Check'
description: 'GitHub Action for running Lighthouse audits with all the bells and whistles 🔔 Multiple audits, Slack notifications and more!'
inputs:
  author:
    description: 'For Slack notifications: A user handle, typically from GitHub.'
  awsAccessKeyId:
    description: 'The AWS accessKeyId for an S3 bucket.'
  awsBucket:
    description: 'The AWS Bucket for an S3 bucket.'
  awsRegion:
    description: 'The AWS region for an S3 bucket.'
  awsSecretAccessKey:
    description: 'The AWS secretAccessKey for an S3 bucket.'
  branch:
    description: 'For Slack notifications: A version control branch, typically from GitHub.'
  configFile:
    description: 'A configuration file path in JSON format which holds all options defined here. This file should be relative to the file being interpretted. In this case it will most likely be the root of the repo ("./")'
  emulatedFormFactor:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module for details.'
  locale:
    description: 'A locale for Lighthouse reports. Example: ja'
  outputDirectory:
    description: 'An absolute directory path to output report. You can do this an an alternative or combined with an S3 upload.'
  pr:
    description: 'For Slack notifications: A version control pull request URL, typically from GitHub.'
  accessToken:
    description: 'Access token of a user to post PR comments.'
  sha:
    description: 'For Slack notifications: A version control sha, typically from GitHub.'
  slackWebhookUrl:
    description: 'A Slack Incoming Webhook URL to send notifications to.'
  throttlingMethod:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module comments for details.'
  throttling:
    description: 'Lighthouse setting only used for local audits. See lighthouse-check NPM module comments for details.'
  urls:
    description: 'A comma-separated list of URLs to run Lighthouse audits against.'
  verbose:
    description: 'If yes, logs output along each step.'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'zap'  
  color: 'green'