name: Test Automated Lighthouse Check
on: [pull_request]

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir /tmp/artifacts
    - name: Run Lighthouse
      uses: ./
      with:
        accessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        apiToken: ${{ secrets.LIGHTHOUSE_CHECK_API_TOKEN }}
        tag: GitHub Action
        urls: ${{ secrets.LIGHTHOUSE_CHECK_URLS }}
