name: Test Comment on Push
on:
  push:
    branches:
      - master

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'
    - name: Run Lighthouse
      uses: ./
      with:
        commentUrl: https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments
        gitHubAccessToken: ${{ secrets.GITHUB_TOKEN }}
        prCommentEnabled: true
        urls: 'https://www.foo.software'
