name: Test Comment on Push
on:
  push:
    branches:
      - master

jobs:
  lighthouse-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Run Lighthouse
      uses: ./
      with:
        commentUrl: https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/comments
        gitHubAccessToken: ${{ secrets.LIGHTHOUSE_CHECK_GITHUB_ACCESS_TOKEN }}
        prCommentEnabled: true
        urls: 'https://www.foo.software'
