name: Test on Deployment
on:
  deployment_status:
    branches:
      - '*'

jobs:
  deployment-test:
    runs-on: ubuntu-latest
    if: github.event.deployment_status.state == 'success'
    steps:
      - uses: actions/checkout@master
      - name: Log deploy URL
        run: |
          echo "deploy URL ${{ github.event.deployment_status.target_url }}"
